# Understanding Numberical Operations with numpy

## 2D Array in Numpy

In [2]:
import numpy as np;

In [4]:
x=[[10,20,30],[40,50,60],[70,80,90]]

In [6]:
x

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

Another way to create same nested list :

In [8]:
y=[list(range(10,31,10)), list(range(40,61,10)), list(range(70,91,10))]

In [10]:
y

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

### covert into numpy array:

In [16]:
xnp= np.array(x)
xnp

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Indexing

Normal Array :

In [20]:
x[0]

[10, 20, 30]

In [22]:
x[0][1]

20

In [24]:
x[0][-1]

30

NumPy Array :

In [28]:
xnp[0][1]

20

We can do it same like normal array like above example ,
But below is approch in numpy

In [34]:
xnp[0,1]

20

In [36]:
xnp[0,-1]

30

## Slicing

In [41]:
x[0:2]

[[10, 20, 30], [40, 50, 60]]

In [43]:
xnp

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [45]:
xnp[0:2, 1:3]

array([[20, 30],
       [50, 60]])

in above example the first argument in slcing is for rows extraction & second argment is for column extraction....this approch cant use in normal arrays 

In [48]:
xnp[0]

array([10, 20, 30])

if i want specific colum from specific row --->

In [51]:
xnp[1,1:3]

array([50, 60])

## Logical Indexing 

In [55]:
xnp

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
xnp>50

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

if want element which are greater than 50

In [66]:
xnp[xnp>50]

array([60, 70, 80, 90])

In [68]:
xnp[: , 2]

array([30, 60, 90])

In [75]:
xnp[:, 2]> 50

array([False,  True,  True])

.

.



# Functions in NumPy

In [ ]:
import numpy as np 

### create a array

...arange function creates an numpy array with specific start & end element with indexing

In [93]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [95]:
np.arange(4,8)

array([4, 5, 6, 7])

In [97]:
np.arange(1 ,10,2)

array([1, 3, 5, 7, 9])

**numpy.linspace()** is a function within the NumPy library in Python used to generate an array of evenly spaced numbers over a specified interval.
Evenly Spaced Values: It creates a sequence of numbers where the difference between consecutive values is constant (linear spacing).

In [101]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

so **linspace** fucnction generates 100 numbers between 1 to 10 where in each value there is constant diffrence
.
.
.

.

The **numpy.logspace()** function in Python's NumPy library generates an array of numbers that are evenly spaced on a logarithmic scale. This function is particularly useful when working with data that spans several orders of magnitude or when creating scales for logarithmic plots.

In [104]:
np.logspace(0,5,10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

## Reshaping an ARRAY

In [121]:
x=np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Get the size and shape

In [126]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [128]:
x.size

12

In [130]:
x.shape

(12,)

In [136]:
y=x.reshape(4,3)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [138]:
y.shape

(4, 3)

## Check truth value of an ARRay

In [141]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [143]:
x.any()

True

In [145]:
x.all()

True

## Transpose


In [148]:
x.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [150]:
x.reshape(4,3).T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## MATHS

In [156]:
y=x.reshape(4,3)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [158]:
y+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [168]:
z= np.arange(4).reshape(4,1)
z

array([[0],
       [1],
       [2],
       [3]])

In [172]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [174]:
y+z

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

## Statistical Summary

In [177]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [179]:
x.sum()

78

In [181]:
x.mean()

6.5

In [183]:
x.max()

12

In [185]:
x.min()

1

standard deviation : std

In [188]:
x.std()

3.452052529534663

product : prod()

In [191]:
x.prod()

479001600

In [193]:
import os

In [195]:
print(os.getcwd())

C:\Users\yashraj


# random numbers and distribution in NUMPY

In [6]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
np.random.seed(123)

In [10]:
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])