# 1D Arryas with Numpy

In [23]:
import numpy as np

In [25]:
x=[100, 200, 300,400]

In [27]:
x

[100, 200, 300, 400]

In [33]:
y=np.array(x)
y

array([100, 200, 300, 400])

In [35]:
type(x)

list

In [37]:
type(y)

numpy.ndarray

Normal array + : concatenation

In [39]:
x+x

[100, 200, 300, 400, 100, 200, 300, 400]

numpy array + : actual addition 

In [41]:
y+y


array([200, 400, 600, 800])

In [43]:
y*y


array([ 10000,  40000,  90000, 160000])

## Subseting & slicing 

In [50]:
y

array([100, 200, 300, 400])

In [58]:
y[0]

100

In [60]:
y[:3]

array([100, 200, 300])

In [62]:
y[2:3]

array([300])

In [64]:
y[::]

array([100, 200, 300, 400])

In [66]:
y[0:]

array([100, 200, 300, 400])

In [70]:
y[-1]   

400

In [74]:
y[-3:-1]

array([200, 300])

## Logical Indexing

In [86]:
y

array([100, 200, 300, 400])

In [88]:
y> 200

array([False, False,  True,  True])

In [90]:
y==300

array([False, False,  True, False])

In [92]:
y!=200

array([ True, False,  True,  True])

In [94]:
y[y>200]

array([300, 400])